/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagement.system;

/**
 *
 * @author it's Anivesh
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentPage
     */
    public StudentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Schoolname1 = new javax.swing.JLabel();
        Schoolname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backclick = new javax.swing.JLabel();
        attendence = new javax.swing.JButton();
        addstudent = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        editstudent = new javax.swing.JButton();
        searchanddelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student.png"))); // NOI18N

        Schoolname1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Schoolname1.setForeground(new java.awt.Color(255, 255, 255));
        Schoolname1.setText(" School Management");

        Schoolname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Schoolname.setForeground(new java.awt.Color(255, 255, 255));
        Schoolname.setText("System");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("© Copyright 2024 anivesh. All rights reserved");

        backclick.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        backclick.setForeground(new java.awt.Color(255, 255, 255));
        backclick.setText("<Back");
        backclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backclickMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Schoolname1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(backclick, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Schoolname)
                        .addGap(138, 138, 138))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backclick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Schoolname1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Schoolname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(410, 0, 390, 500);

        attendence.setBackground(new java.awt.Color(0, 102, 102));
        attendence.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendence.setForeground(new java.awt.Color(255, 255, 255));
        attendence.setText("ATTENDANCE");
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });
        jPanel1.add(attendence);
        attendence.setBounds(100, 370, 220, 40);

        addstudent.setBackground(new java.awt.Color(0, 102, 102));
        addstudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addstudent.setForeground(new java.awt.Color(255, 255, 255));
        addstudent.setText("ADD STUDENT");
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });
        jPanel1.add(addstudent);
        addstudent.setBounds(100, 190, 220, 40);

        Heading.setBackground(new java.awt.Color(0, 102, 102));
        Heading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 102, 102));
        Heading.setText("STUDENT PAGE");
        jPanel1.add(Heading);
        Heading.setBounds(70, 70, 270, 48);

        editstudent.setBackground(new java.awt.Color(0, 102, 102));
        editstudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editstudent.setForeground(new java.awt.Color(255, 255, 255));
        editstudent.setText("EDIT STUDENT DETAILS");
        editstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editstudentActionPerformed(evt);
            }
        });
        jPanel1.add(editstudent);
        editstudent.setBounds(100, 250, 220, 40);

        searchanddelete.setBackground(new java.awt.Color(0, 102, 102));
        searchanddelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchanddelete.setForeground(new java.awt.Color(255, 255, 255));
        searchanddelete.setText("SEARCH & DELETE");
        searchanddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchanddeleteActionPerformed(evt);
            }
        });
        jPanel1.add(searchanddelete);
        searchanddelete.setBounds(100, 310, 220, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
        // TODO add your handling code here:
        StudentAttendance obj = new StudentAttendance();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_attendenceActionPerformed

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        // TODO add your handling code here:
        AddStudentPage obj = new AddStudentPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_addstudentActionPerformed

    private void editstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editstudentActionPerformed
        // TODO add your handling code here:
        EditStudent obj;
        obj = new EditStudent();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editstudentActionPerformed

    private void backclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backclickMouseClicked
        // TODO add your handling code here:
        Welcome obj = new Welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backclickMouseClicked

    private void searchanddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchanddeleteActionPerformed
        // TODO add your handling code here:
        SearchandDelete obj = new SearchandDelete();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchanddeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Schoolname;
    private javax.swing.JLabel Schoolname1;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton attendence;
    private javax.swing.JLabel backclick;
    private javax.swing.JButton editstudent;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton searchanddelete;
    // End of variables declaration//GEN-END:variables
}
