/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagement.system;

/**
 *
 * @author it's Anivesh
 */
public class TeacherPage extends javax.swing.JFrame {

    /**
     * Creates new form TeacherPage
     */
    public TeacherPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Schoolname1 = new javax.swing.JLabel();
        Schoolname = new javax.swing.JLabel();
        backclick = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        addteacher = new javax.swing.JButton();
        editteacher = new javax.swing.JButton();
        searchanddelete = new javax.swing.JButton();
        attendence = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEACHERS PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pngwing.com (1).png"))); // NOI18N

        Schoolname1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Schoolname1.setForeground(new java.awt.Color(255, 255, 255));
        Schoolname1.setText(" School Management");

        Schoolname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Schoolname.setForeground(new java.awt.Color(255, 255, 255));
        Schoolname.setText("System");

        backclick.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        backclick.setForeground(new java.awt.Color(255, 255, 255));
        backclick.setText("<Back");
        backclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backclickMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("© Copyright 2024 anivesh. All rights reserved");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(124, 124, 124))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(Schoolname1)
                            .addGap(66, 66, 66))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(backclick, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(Schoolname)
                            .addGap(138, 138, 138)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backclick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Schoolname1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Schoolname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 0, 400, 500);

        Heading.setBackground(new java.awt.Color(0, 102, 102));
        Heading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 102, 102));
        Heading.setText("TEACHER PAGE");
        jPanel1.add(Heading);
        Heading.setBounds(70, 50, 270, 48);

        addteacher.setBackground(new java.awt.Color(0, 102, 102));
        addteacher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addteacher.setForeground(new java.awt.Color(255, 255, 255));
        addteacher.setText("ADD TEACHER");
        addteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addteacherActionPerformed(evt);
            }
        });
        jPanel1.add(addteacher);
        addteacher.setBounds(100, 160, 220, 40);

        editteacher.setBackground(new java.awt.Color(0, 102, 102));
        editteacher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editteacher.setForeground(new java.awt.Color(255, 255, 255));
        editteacher.setText("EDIT TEACHER DETAILS");
        editteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editteacherActionPerformed(evt);
            }
        });
        jPanel1.add(editteacher);
        editteacher.setBounds(100, 220, 220, 40);

        searchanddelete.setBackground(new java.awt.Color(0, 102, 102));
        searchanddelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchanddelete.setForeground(new java.awt.Color(255, 255, 255));
        searchanddelete.setText("SEARCH & DELETE");
        searchanddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchanddeleteActionPerformed(evt);
            }
        });
        jPanel1.add(searchanddelete);
        searchanddelete.setBounds(100, 280, 220, 40);

        attendence.setBackground(new java.awt.Color(0, 102, 102));
        attendence.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendence.setForeground(new java.awt.Color(255, 255, 255));
        attendence.setText("ATTENDENCE");
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });
        jPanel1.add(attendence);
        attendence.setBounds(100, 340, 220, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addteacherActionPerformed
        // TODO add your handling code here:
        AddTeacherPage obj =new AddTeacherPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_addteacherActionPerformed

    private void editteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editteacherActionPerformed
        // TODO add your handling code here:
        EditTeacher obj =new EditTeacher();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_editteacherActionPerformed

    private void searchanddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchanddeleteActionPerformed
        // TODO add your handling code here:
        TeacherSearchandDelete obj =new TeacherSearchandDelete();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchanddeleteActionPerformed

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
        // TODO add your handling code here:
        Attendance obj =new Attendance();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_attendenceActionPerformed

    private void backclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backclickMouseClicked
        // TODO add your handling code here:
        Welcome obj =new Welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backclickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Schoolname;
    private javax.swing.JLabel Schoolname1;
    private javax.swing.JButton addteacher;
    private javax.swing.JButton attendence;
    private javax.swing.JLabel backclick;
    private javax.swing.JButton editteacher;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton searchanddelete;
    // End of variables declaration//GEN-END:variables
}
