/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagement.system;
/**
 * 
 *
 * @author it's Anivesh
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Heading1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        studentclick = new javax.swing.JLabel();
        studenttext = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        teacherclick = new javax.swing.JLabel();
        teachertext = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        feeclick = new javax.swing.JLabel();
        feetext = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        gradeclick = new javax.swing.JLabel();
        gradetext = new javax.swing.JLabel();
        Aboutus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        Heading.setBackground(new java.awt.Color(0, 102, 102));
        Heading.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("hey, Welcome");

        Logout.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("<Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("School Management System....");

        Heading1.setBackground(new java.awt.Color(0, 102, 102));
        Heading1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Heading1.setForeground(new java.awt.Color(255, 255, 255));
        Heading1.setText("MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Heading))
                .addGap(18, 18, 18)
                .addComponent(Heading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Heading1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 810, 150);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        studentclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student.png"))); // NOI18N
        studentclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentclickMouseClicked(evt);
            }
        });

        studenttext.setBackground(new java.awt.Color(255, 255, 255));
        studenttext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studenttext.setForeground(new java.awt.Color(0, 102, 102));
        studenttext.setText("STUDENT'S");
        studenttext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(studentclick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studenttext, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(studentclick, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studenttext, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(90, 210, 130, 160);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        teacherclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/system/Teacher.png"))); // NOI18N
        teacherclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherclickMouseClicked(evt);
            }
        });

        teachertext.setBackground(new java.awt.Color(255, 255, 255));
        teachertext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teachertext.setForeground(new java.awt.Color(0, 102, 102));
        teachertext.setText("TEACHER'S");
        teachertext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachertextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherclick, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(teachertext, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(teacherclick, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachertext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(260, 210, 130, 160);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        feeclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cost.png"))); // NOI18N
        feeclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeclickMouseClicked(evt);
            }
        });

        feetext.setBackground(new java.awt.Color(255, 255, 255));
        feetext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feetext.setForeground(new java.awt.Color(0, 102, 102));
        feetext.setText("FEE SECTION");
        feetext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feetextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feeclick, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(feetext, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(feeclick, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feetext, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(420, 210, 130, 160);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        gradeclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exam1.png"))); // NOI18N
        gradeclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeclickMouseClicked(evt);
            }
        });

        gradetext.setBackground(new java.awt.Color(255, 255, 255));
        gradetext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gradetext.setForeground(new java.awt.Color(0, 102, 102));
        gradetext.setText("GRADE'S");
        gradetext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradetextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradeclick, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gradetext, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(gradeclick, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradetext, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(580, 210, 130, 160);

        Aboutus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Aboutus.setForeground(new java.awt.Color(0, 102, 102));
        Aboutus.setText("About us.");
        Aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusMouseClicked(evt);
            }
        });
        jPanel1.add(Aboutus);
        Aboutus.setBounds(660, 420, 70, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("© Copyright 2024 anivesh. All rights reserved");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 440, 236, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Select where you want to go...");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 150, 190, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("WELCOME");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentclickMouseClicked
        // TODO add your handling code here:
        StudentPage obj =new StudentPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_studentclickMouseClicked

    private void teacherclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherclickMouseClicked
        // TODO add your handling code here:
        TeacherPage obj =new TeacherPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_teacherclickMouseClicked

    private void feeclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeclickMouseClicked
        // TODO add your handling code here:
        FeePage obj =new FeePage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_feeclickMouseClicked

    private void gradeclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeclickMouseClicked
        // TODO add your handling code here:
        GradeCard obj =new GradeCard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gradeclickMouseClicked

    private void studenttextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttextMouseClicked
        // TODO add your handling code here:
        StudentPage obj =new StudentPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_studenttextMouseClicked

    private void teachertextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachertextMouseClicked
        // TODO add your handling code here:
        TeacherPage obj =new TeacherPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_teachertextMouseClicked

    private void feetextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feetextMouseClicked
        // TODO add your handling code here:
        FeePage obj =new FeePage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_feetextMouseClicked

    private void gradetextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradetextMouseClicked
        // TODO add your handling code here:
        GradeCard obj =new GradeCard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gradetextMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        LoginPage obj =new LoginPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void AboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMouseClicked
        // TODO add your handling code here:
        Aboutus obj =new Aboutus();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_AboutusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel feeclick;
    private javax.swing.JLabel feetext;
    private javax.swing.JLabel gradeclick;
    private javax.swing.JLabel gradetext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel studentclick;
    private javax.swing.JLabel studenttext;
    private javax.swing.JLabel teacherclick;
    private javax.swing.JLabel teachertext;
    // End of variables declaration//GEN-END:variables
}
